# Generated by Django 3.1.5 on 2021-01-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar_course_name', models.CharField(max_length=20)),
                ('calendar_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('calendar_image_keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEvidence',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('employee_paragraph', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentCompany',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=20)),
                ('job_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_firstname', models.CharField(max_length=20)),
                ('publisher_lastname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=100)),
                ('event_subtitle', models.CharField(max_length=100)),
                ('event_text', models.CharField(max_length=10000)),
                ('event_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.eventimage')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentOpportunity',
            fields=[
                ('employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employment_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.employmentcompany')),
            ],
        ),
        migrations.AddField(
            model_name='employmentcompany',
            name='company_job_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.jobopportunity'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_date', models.DateField()),
                ('article_title', models.CharField(max_length=100)),
                ('article_subtitle', models.CharField(max_length=100)),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('article_text', models.CharField(max_length=10000)),
                ('article_keywords_image', models.CharField(max_length=100)),
                ('article_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.publisher')),
            ],
        ),
    ]
