# Generated by Django 3.1.5 on 2021-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employeeevidence',
            name='employee_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_text',
            field=models.TextField(),
        ),
    ]
