# Generated by Django 3.1.3 on 2021-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210210_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
