# Generated by Django 3.1.3 on 2021-02-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210210_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
