# Generated by Django 3.1.3 on 2021-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_email',
            field=models.CharField(max_length=30),
        ),
    ]
