# Generated by Django 3.1.3 on 2021-02-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210211_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_img',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.event'),
        ),
    ]
