# Generated by Django 3.1.3 on 2021-02-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210212_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_event',
            new_name='event_id',
        ),
    ]
