# Generated by Django 3.1.3 on 2021-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_event_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_image_keywords',
            field=models.CharField(default='event', max_length=100),
        ),
    ]
