# Generated by Django 3.1.3 on 2021-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210212_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calendar_course_name',
            field=models.CharField(max_length=25),
        ),
    ]
